// Licensed under the MIT License
// https://github.com/sator-imaging/StaticMemberAnalyzer

using Microsoft.VisualStudio.TestTools.UnitTesting;
using SatorImaging.StaticMemberAnalyzer.Analysis;
using SatorImaging.StaticMemberAnalyzer.CodeFixes;
using System.Linq;

namespace SatorImaging.StaticMemberAnalyzer.Test
{
    // NOTE: This test is for adjusting test coverage numbers.
    //       Don't need to check machine-generated properties preciously.
    [TestClass]
    public class ResourceStringTest
    {
        [TestMethod]
        public void AllResourceProperties_And_BurstLinq()
        {
            // ResourceManager property checks
            _ = new Resources();
            Resources.Culture = Resources.Culture;
            _ = new CodeFixResources();
            CodeFixResources.Culture = CodeFixResources.Culture;

            Assert.IsNotNull(Resources.ResourceManager);
            Assert.IsNotNull(CodeFixResources.ResourceManager);

            // All Analysis Resources string properties
            var analysisProps = new string[]
            {
                Resources.SMA0001__MD_TITLE__,
                Resources.SMA0001_Description,
                Resources.SMA0001_MessageFormat,
                Resources.SMA0001_Title,
                Resources.SMA0002_Description,
                Resources.SMA0002_MessageFormat,
                Resources.SMA0002_Title,
                Resources.SMA0003_Description,
                Resources.SMA0003_MessageFormat,
                Resources.SMA0003_Title,
                Resources.SMA0004_Description,
                Resources.SMA0004_MessageFormat,
                Resources.SMA0004_Title,
                Resources.SMA0010__MD_TITLE__,
                Resources.SMA0010_Description,
                Resources.SMA0010_MessageFormat,
                Resources.SMA0010_Title,
                Resources.SMA0011_Description,
                Resources.SMA0011_MessageFormat,
                Resources.SMA0011_Title,
                Resources.SMA0012_Description,
                Resources.SMA0012_MessageFormat,
                Resources.SMA0012_Title,
                Resources.SMA0015_Description,
                Resources.SMA0015_MessageFormat,
                Resources.SMA0015_Title,
                Resources.SMA0020__MD_TITLE__,
                Resources.SMA0020_Description,
                Resources.SMA0020_MessageFormat,
                Resources.SMA0020_Title,
                Resources.SMA0021_Description,
                Resources.SMA0021_MessageFormat,
                Resources.SMA0021_Title,
                Resources.SMA0022_Description,
                Resources.SMA0022_MessageFormat,
                Resources.SMA0022_Title,
                Resources.SMA0023_Description,
                Resources.SMA0023_MessageFormat,
                Resources.SMA0023_Title,
                Resources.SMA0024_Description,
                Resources.SMA0024_MessageFormat,
                Resources.SMA0024_Title,
                Resources.SMA0025_Description,
                Resources.SMA0025_MessageFormat,
                Resources.SMA0025_Title,
                Resources.SMA0026_Description,
                Resources.SMA0026_MessageFormat,
                Resources.SMA0026_Title,
                Resources.SMA0027_Description,
                Resources.SMA0027_MessageFormat,
                Resources.SMA0027_Title,
                Resources.SMA0028_Description,
                Resources.SMA0028_MessageFormat,
                Resources.SMA0028_Title,
                Resources.SMA0030__MD_TITLE__,
                Resources.SMA0030_Description,
                Resources.SMA0030_MessageFormat,
                Resources.SMA0030_Title,
                Resources.SMA0031_Description,
                Resources.SMA0031_MessageFormat,
                Resources.SMA0031_Title,
                Resources.SMA0032_Description,
                Resources.SMA0032_MessageFormat,
                Resources.SMA0032_Title,
                Resources.SMA0040__MD_TITLE__,
                Resources.SMA0040_Description,
                Resources.SMA0040_MessageFormat,
                Resources.SMA0040_Title,
                Resources.SMA0041_Description,
                Resources.SMA0041_MessageFormat,
                Resources.SMA0041_Title,
                Resources.SMA0042_Description,
                Resources.SMA0042_MessageFormat,
                Resources.SMA0042_Title,
                Resources.SMA0043_Description,
                Resources.SMA0043_MessageFormat,
                Resources.SMA0043_Title,
                Resources.SMA0044_Description,
                Resources.SMA0044_MessageFormat,
                Resources.SMA0044_Title,
                Resources.SMA0045_Description,
                Resources.SMA0045_MessageFormat,
                Resources.SMA0045_Title,
                Resources.SMA0050__MD_TITLE__,
                Resources.SMA0050_Description,
                Resources.SMA0050_MessageFormat,
                Resources.SMA0050_Title,
                Resources.SMA0060__MD_TITLE__,
                Resources.SMA0060_Description,
                Resources.SMA0060_MessageFormat,
                Resources.SMA0060_Title,
                Resources.SMA0061_Description,
                Resources.SMA0061_MessageFormat,
                Resources.SMA0061_Title,
                Resources.SMA0062_Description,
                Resources.SMA0062_MessageFormat,
                Resources.SMA0062_Title,
                Resources.SMA0063_Description,
                Resources.SMA0063_MessageFormat,
                Resources.SMA0063_Title,
                Resources.SMA0064_Description,
                Resources.SMA0064_MessageFormat,
                Resources.SMA0064_Title,
                Resources.SMA0070__MD_TITLE__,
                Resources.SMA0070_Description,
                Resources.SMA0070_MessageFormat,
                Resources.SMA0070_Title,
                Resources.SMA0071_Description,
                Resources.SMA0071_MessageFormat,
                Resources.SMA0071_Title,
                Resources.SMA0080__MD_TITLE__,
                Resources.SMA0080_Description,
                Resources.SMA0080_MessageFormat,
                Resources.SMA0080_Title,
                Resources.SMA7000__MD_TITLE__,
                Resources.SMA7000_Description,
                Resources.SMA7000_MessageFormat,
                Resources.SMA7000_Title,
                Resources.SMA7001_Description,
                Resources.SMA7001_MessageFormat,
                Resources.SMA7001_Title,
                Resources.SMA7002_Description,
                Resources.SMA7002_MessageFormat,
                Resources.SMA7002_Title,
                Resources.SMA7010_Description,
                Resources.SMA7010_MessageFormat,
                Resources.SMA7010_Title,
                Resources.SMA7011_Description,
                Resources.SMA7011_MessageFormat,
                Resources.SMA7011_Title,
                Resources.SMA8000__MD_TITLE__,
                Resources.SMA8000_Description,
                Resources.SMA8000_MessageFormat,
                Resources.SMA8000_Title,
                Resources.SMA8001_Description,
                Resources.SMA8001_MessageFormat,
                Resources.SMA8001_Title,
                Resources.SMA8002_Description,
                Resources.SMA8002_MessageFormat,
                Resources.SMA8002_Title,
                Resources.SMA9000__MD_TITLE__,
                Resources.SMA9000_Description,
                Resources.SMA9000_MessageFormat,
                Resources.SMA9000_Title,
                Resources.SMA9001_Description,
                Resources.SMA9001_MessageFormat,
                Resources.SMA9001_Title,
                Resources.SMA9002_Description,
                Resources.SMA9002_MessageFormat,
                Resources.SMA9002_Title,
                Resources.SMA9010_Description,
                Resources.SMA9010_MessageFormat,
                Resources.SMA9010_Title,
                Resources.SMA9015_Description,
                Resources.SMA9015_MessageFormat,
                Resources.SMA9015_Title,
                Resources.SMA9020_Description,
                Resources.SMA9020_MessageFormat,
                Resources.SMA9020_Title,
                Resources.SMA9021_Description,
                Resources.SMA9021_MessageFormat,
                Resources.SMA9021_Title,
                Resources.SMA9022_Description,
                Resources.SMA9022_MessageFormat,
                Resources.SMA9022_Title,
                Resources.SMA9023_Description,
                Resources.SMA9023_MessageFormat,
                Resources.SMA9023_Title,
                Resources.SMA9100_Description,
                Resources.SMA9100_MessageFormat,
                Resources.SMA9100_Title,
            };
            Assert.IsTrue(analysisProps.All(p => p != null));

            // All CodeFix Resources string properties
            var codefixProps = new string[]
            {
                CodeFixResources.CodeFix_EnumObfuscation,
                CodeFixResources.CodeFix_NamedArgument,
                CodeFixResources.CodeFix_NullSuppression,
            };
            Assert.IsTrue(codefixProps.All(p => p != null));
        }
    }
}
