// Licensed under the MIT License
// https://github.com/sator-imaging/MeticulousAnalyzer

// <auto-generated>
//     This code was generated by eng/RegexGen.cs helper.
// </auto-generated>

using System.Text.RegularExpressions;

namespace SatorImaging.MeticulousAnalyzer.Analysis.Analyzers
{
    public static class LiteralBranchRegexHelper
    {
        public static readonly Regex MatchingMemberNameRegex = new Regex(
            @"Length|Count|Index|Remove|Search|Add|Exchange|Decrement|Increment",
            RegexOptions.Compiled | RegexOptions.IgnoreCase);
    }
}
