// Licensed under the MIT License
// https://github.com/sator-imaging/MeticulousAnalyzer

// <auto-generated>
//     This code was extracted from .NET RegexGenerator source generator output by eng/RegexGen.cs helper.
//     Converted to string-matching code WITHOUT Regex or .NET 7+ runtime dependency.
// </auto-generated>

using System;

namespace SatorImaging.MeticulousAnalyzer.Analysis.Analyzers
{
    public static class LiteralBranchRegexHelper
    {
        public static bool IsMatch(string name)
        {
            if (string.IsNullOrEmpty(name))
                return false;

            return name.IndexOf("Length", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf("Count", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf("Index", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf("Remove", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf("Search", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf("Add", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf("Exchange", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf("Decrement", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf("Increment", StringComparison.OrdinalIgnoreCase) >= 0;
        }
    }
}