// Licensed under the MIT License
// https://github.com/sator-imaging/MeticulousAnalyzer

#:property LangVersion=latest

using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

string outputPath = args.Length > 0 && !string.IsNullOrWhiteSpace(args[0])
    ? args[0]
    : "src/analysis/Analyzers/LiteralBranchAnalyzer.GeneratedRegex.cs";

const string pattern = @"Length|Count|Index|Remove|Search|Add|Exchange|Decrement|Increment";

var sb = new StringBuilder();
sb.AppendLine("// Licensed under the MIT License");
sb.AppendLine("// https://github.com/sator-imaging/MeticulousAnalyzer");
sb.AppendLine();
sb.AppendLine("// <auto-generated>");
sb.AppendLine("//     This code was generated by eng/RegexGen.cs helper.");
sb.AppendLine("// </auto-generated>");
sb.AppendLine();
sb.AppendLine("using System.Text.RegularExpressions;");
sb.AppendLine();
sb.AppendLine("namespace SatorImaging.MeticulousAnalyzer.Analysis.Analyzers");
sb.AppendLine("{");
sb.AppendLine("    public static class LiteralBranchRegexHelper");
sb.AppendLine("    {");
sb.AppendLine("        public static readonly Regex MatchingMemberNameRegex = new Regex(");
sb.AppendLine($"            @\"{pattern}\",");
sb.AppendLine("            RegexOptions.Compiled | RegexOptions.IgnoreCase);");
sb.AppendLine("    }");
sb.AppendLine("}");

var dirPath = Path.GetDirectoryName(outputPath);
if (!string.IsNullOrWhiteSpace(dirPath) && !Directory.Exists(dirPath))
{
    Directory.CreateDirectory(dirPath);
}

File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
Console.WriteLine($"Generated compiled regex source code at: {outputPath}");

return 0;
