// Licensed under the MIT License
// https://github.com/sator-imaging/MeticulousAnalyzer

#:property LangVersion=latest
#:property TargetFramework=net10.0
#:property PublishAot=false

using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;

namespace SatorImaging.MeticulousAnalyzer.Eng
{
    public static class RegexGen
    {
        public static int Main(string[] args)
        {
            string outputPath = args.Length > 0 && !string.IsNullOrWhiteSpace(args[0])
                ? args[0]
                : "src/analysis/Analyzers/LiteralBranchAnalyzer.GeneratedRegex.cs";

            string tempDir = Path.Combine(Path.GetTempPath(), "MeticulousAnalyzer_RegexGen_" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(tempDir);

            try
            {
                string csprojPath = Path.Combine(tempDir, "GenApp.csproj");
                string csprojContent = @"<Project Sdk=""Microsoft.NET.Sdk"">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)GeneratedFiles</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
</Project>";
                File.WriteAllText(csprojPath, csprojContent);

                string programPath = Path.Combine(tempDir, "Program.cs");
                string programContent = @"using System;
using System.Text.RegularExpressions;

namespace SatorImaging.MeticulousAnalyzer.Analysis.Analyzers;

public static partial class LiteralBranchRegexHelper
{
    [GeneratedRegex(@""Length|Count|Index|Remove|Search|Add|Exchange|Decrement|Increment"", RegexOptions.IgnoreCase)]
    public static partial Regex MatchingMemberNameRegex();
}

class Program
{
    static void Main() => Console.WriteLine(LiteralBranchRegexHelper.MatchingMemberNameRegex().IsMatch(""Length""));
}";
                File.WriteAllText(programPath, programContent);

                var psi = new ProcessStartInfo("dotnet", $"build \"{csprojPath}\"")
                {
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false
                };
                using var proc = Process.Start(psi);
                if (proc != null)
                {
                    proc.WaitForExit();
                }

                string? generatedFile = Directory.GetFiles(tempDir, "*RegexGenerator.g.cs", SearchOption.AllDirectories).FirstOrDefault();
                // Early exit
                if (generatedFile == null)
                {
                    Console.Error.WriteLine("Failed to locate generated RegexGenerator.g.cs");
                    return 1;
                }

                string rawCode = File.ReadAllText(generatedFile);

                // Convert compiler-generated output into code that does NOT depend on Regex / net7+ / SearchValues / file types
                string convertedCode = @"// Licensed under the MIT License
// https://github.com/sator-imaging/MeticulousAnalyzer

// <auto-generated>
//     This code was extracted from .NET RegexGenerator source generator output by eng/RegexGen.cs helper.
//     Converted to string-matching code WITHOUT Regex or .NET 7+ runtime dependency.
// </auto-generated>

using System;

namespace SatorImaging.MeticulousAnalyzer.Analysis.Analyzers
{
    public static class LiteralBranchRegexHelper
    {
        public static bool IsMatch(string name)
        {
            if (string.IsNullOrEmpty(name))
                return false;

            return name.IndexOf(""Length"", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf(""Count"", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf(""Index"", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf(""Remove"", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf(""Search"", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf(""Add"", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf(""Exchange"", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf(""Decrement"", StringComparison.OrdinalIgnoreCase) >= 0 ||
                   name.IndexOf(""Increment"", StringComparison.OrdinalIgnoreCase) >= 0;
        }
    }
}";

                var dirPath = Path.GetDirectoryName(outputPath);
                if (!string.IsNullOrWhiteSpace(dirPath) && !Directory.Exists(dirPath))
                {
                    Directory.CreateDirectory(dirPath);
                }

                File.WriteAllText(outputPath, convertedCode);
                Console.WriteLine($"Extracted and converted source generator output at: {outputPath}");
                return 0;
            }
            finally
            {
                try
                {
                    Directory.Delete(tempDir, recursive: true);
                }
                catch (IOException ex)
                {
                    Console.Error.WriteLine(ex.Message);
                }
                catch (UnauthorizedAccessException ex)
                {
                    Console.Error.WriteLine(ex.Message);
                }
            }
        }
    }
}
