// <auto-generated>
//     Source generated files collected:
//     - RegexGenerator.g.cs
//     Patterns:
//     - IsExcemptionNameForZeroComparison: @"Length|Count|Index|Remove|Search|Add|Exchange|Decrement|Increment", RegexOptions.IgnoreCase
// </auto-generated>

namespace SatorImaging.MeticulousAnalyzer.Analysis
{
    public static partial class GeneratedRegexPolyfill
    {
        public static partial global::System.Text.RegularExpressions.Regex IsExcemptionNameForZeroComparison();
    }
}

// <auto-generated/>
#nullable enable
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // Unreferenced label
#pragma warning disable CS0219 // Variable assigned but never used

namespace SatorImaging.MeticulousAnalyzer.Analysis
{
    partial class GeneratedRegexPolyfill
    {
        /// <remarks>
        /// Pattern explanation:<br/>
        /// <code>
        /// ○ Match with 9 alternative expressions, atomically.<br/>
        ///     ○ Match a sequence of expressions.<br/>
        ///         ○ Match a character in the set [Ll].<br/>
        ///         ○ Match a character in the set [Ee].<br/>
        ///         ○ Match a character in the set [Nn].<br/>
        ///         ○ Match a character in the set [Gg].<br/>
        ///         ○ Match a character in the set [Tt].<br/>
        ///         ○ Match a character in the set [Hh].<br/>
        ///     ○ Match a sequence of expressions.<br/>
        ///         ○ Match a character in the set [Cc].<br/>
        ///         ○ Match a character in the set [Oo].<br/>
        ///         ○ Match a character in the set [Uu].<br/>
        ///         ○ Match a character in the set [Nn].<br/>
        ///         ○ Match a character in the set [Tt].<br/>
        ///     ○ Match a sequence of expressions.<br/>
        ///         ○ Match a character in the set [Ii].<br/>
        ///         ○ Match a character in the set [Nn].<br/>
        ///         ○ Match a character in the set [Dd].<br/>
        ///         ○ Match a character in the set [Ee].<br/>
        ///         ○ Match a character in the set [Xx].<br/>
        ///     ○ Match a sequence of expressions.<br/>
        ///         ○ Match a character in the set [Rr].<br/>
        ///         ○ Match a character in the set [Ee].<br/>
        ///         ○ Match a character in the set [Mm].<br/>
        ///         ○ Match a character in the set [Oo].<br/>
        ///         ○ Match a character in the set [Vv].<br/>
        ///         ○ Match a character in the set [Ee].<br/>
        ///     ○ Match a sequence of expressions.<br/>
        ///         ○ Match a character in the set [Ss].<br/>
        ///         ○ Match a character in the set [Ee].<br/>
        ///         ○ Match a character in the set [Aa].<br/>
        ///         ○ Match a character in the set [Rr].<br/>
        ///         ○ Match a character in the set [Cc].<br/>
        ///         ○ Match a character in the set [Hh].<br/>
        ///     ○ Match a sequence of expressions.<br/>
        ///         ○ Match a character in the set [Aa].<br/>
        ///         ○ Match a character in the set [Dd] exactly 2 times.<br/>
        ///     ○ Match a sequence of expressions.<br/>
        ///         ○ Match a character in the set [Ee].<br/>
        ///         ○ Match a character in the set [Xx].<br/>
        ///         ○ Match a character in the set [Cc].<br/>
        ///         ○ Match a character in the set [Hh].<br/>
        ///         ○ Match a character in the set [Aa].<br/>
        ///         ○ Match a character in the set [Nn].<br/>
        ///         ○ Match a character in the set [Gg].<br/>
        ///         ○ Match a character in the set [Ee].<br/>
        ///     ○ Match a sequence of expressions.<br/>
        ///         ○ Match a character in the set [Dd].<br/>
        ///         ○ Match a character in the set [Ee].<br/>
        ///         ○ Match a character in the set [Cc].<br/>
        ///         ○ Match a character in the set [Rr].<br/>
        ///         ○ Match a character in the set [Ee].<br/>
        ///         ○ Match a character in the set [Mm].<br/>
        ///         ○ Match a character in the set [Ee].<br/>
        ///         ○ Match a character in the set [Nn].<br/>
        ///         ○ Match a character in the set [Tt].<br/>
        ///     ○ Match a sequence of expressions.<br/>
        ///         ○ Match a character in the set [Ii].<br/>
        ///         ○ Match a character in the set [Nn].<br/>
        ///         ○ Match a character in the set [Cc].<br/>
        ///         ○ Match a character in the set [Rr].<br/>
        ///         ○ Match a character in the set [Ee].<br/>
        ///         ○ Match a character in the set [Mm].<br/>
        ///         ○ Match a character in the set [Ee].<br/>
        ///         ○ Match a character in the set [Nn].<br/>
        ///         ○ Match a character in the set [Tt].<br/>
        /// </code>
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "7.0.10.26716")]
        public static partial global::System.Text.RegularExpressions.Regex IsExcemptionNameForZeroComparison() => global::System.Text.RegularExpressions.Generated.IsExcemptionNameForZeroComparison_0.Instance;
    }
}

namespace System.Text.RegularExpressions.Generated
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections;
    using System.ComponentModel;
    using System.Globalization;
    using System.Runtime.CompilerServices;
    using System.Text.RegularExpressions;
    using System.Threading;

    /// <summary>Custom <see cref="Regex"/>-derived type for the IsExcemptionNameForZeroComparison method.</summary>
    [GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "7.0.10.26716")]
    internal sealed class IsExcemptionNameForZeroComparison_0 : Regex
    {
        /// <summary>Cached, thread-safe singleton instance.</summary>
        internal static readonly IsExcemptionNameForZeroComparison_0 Instance = new();

        /// <summary>Initializes the instance.</summary>
        private IsExcemptionNameForZeroComparison_0()
        {
            base.pattern = "Length|Count|Index|Remove|Search|Add|Exchange|Decrement|Increment";
            base.roptions = RegexOptions.IgnoreCase;
            ValidateMatchTimeout(Utilities.s_defaultTimeout);
            base.internalMatchTimeout = Utilities.s_defaultTimeout;
            base.factory = new RunnerFactory();
            base.capsize = 1;
        }

        /// <summary>Provides a factory for creating <see cref="RegexRunner"/> instances to be used by methods on <see cref="Regex"/>.</summary>
        private sealed class RunnerFactory : RegexRunnerFactory
        {
            /// <summary>Creates an instance of a <see cref="RegexRunner"/> used by methods on <see cref="Regex"/>.</summary>
            protected override RegexRunner CreateInstance() => new Runner();

            /// <summary>Provides the runner that contains the custom logic implementing the specified regular expression.</summary>
            private sealed class Runner : RegexRunner
            {
    protected override void Go()
    {
        int start = runtextpos;

        if (!TryMatchAtCurrentPosition(runtext.AsSpan(0, runtextend)))
        {
            runtextpos = start;
        }
    }

    protected override bool FindFirstChar()
    {
        return TryFindNextPossibleStartingPosition(
            runtext.AsSpan(0, runtextend));
    }

    protected override void InitTrackCount()
    {
        runtrackcount = 0;
    }

                /// <summary>Scan the <paramref name="inputSpan"/> starting from base.runtextstart for the next match.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                void Scan(ReadOnlySpan<char> inputSpan)
                {
                    // Search until we can't find a valid starting position, we find a match, or we reach the end of the input.
                    while (TryFindNextPossibleStartingPosition(inputSpan) &&
                           !TryMatchAtCurrentPosition(inputSpan) &&
                           base.runtextpos != inputSpan.Length)
                    {
                        base.runtextpos++;
                        if (Utilities.s_hasTimeout)
                        {
                            base.CheckTimeout();
                        }
                    }
                }

                /// <summary>Search <paramref name="inputSpan"/> starting from base.runtextpos for the next location a match could possibly start.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if a possible match was found; false if no more matches are possible.</returns>
                private bool TryFindNextPossibleStartingPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    ulong charMinusLow;

                    // Any possible match is at least 3 characters.
                    if (pos <= inputSpan.Length - 3)
                    {
                        // The pattern begins with a character in the set [AC-EILRSac-eilrs].
                        // Find the next occurrence. If it can't be found, there's no match.
                        ReadOnlySpan<char> span = inputSpan.Slice(pos);
                        for (int i = 0; i < span.Length - 2; i++)
                        {
                            if (((long)((0xB8906000B8906000UL << (int)(charMinusLow = (uint)span[i] - 'A')) & (charMinusLow - 64)) < 0) &&
                                ((long)((0xC0300800C0300800UL << (int)(charMinusLow = (uint)span[i + 1] - 'D')) & (charMinusLow - 64)) < 0) &&
                                ((long)((0xB00C0800B00C0800UL << (int)(charMinusLow = (uint)span[i + 2] - 'A')) & (charMinusLow - 64)) < 0))
                            {
                                base.runtextpos = pos + i;
                                return true;
                            }
                        }
                    }

                    // No match found.
                    base.runtextpos = inputSpan.Length;
                    return false;
                }

                /// <summary>Determine whether <paramref name="inputSpan"/> at base.runtextpos is a match for the regular expression.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if the regular expression matches at the current position; otherwise, false.</returns>
                private bool TryMatchAtCurrentPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    int matchStart = pos;
                    ReadOnlySpan<char> slice = inputSpan.Slice(pos);

                    // Match with 9 alternative expressions, atomically.
                    {
                        int alternation_starting_pos = pos;

                        // Branch 0
                        {
                            if ((uint)slice.Length < 6 ||
                                !slice.StartsWith("length".AsSpan(), StringComparison.OrdinalIgnoreCase)) // Match the string "length" (ordinal case-insensitive)
                            {
                                goto AlternationBranch;
                            }

                            pos += 6;
                            slice = inputSpan.Slice(pos);
                            goto AlternationMatch;

                            AlternationBranch:
                            pos = alternation_starting_pos;
                            slice = inputSpan.Slice(pos);
                        }

                        // Branch 1
                        {
                            if ((uint)slice.Length < 5 ||
                                !slice.StartsWith("count".AsSpan(), StringComparison.OrdinalIgnoreCase)) // Match the string "count" (ordinal case-insensitive)
                            {
                                goto AlternationBranch1;
                            }

                            pos += 5;
                            slice = inputSpan.Slice(pos);
                            goto AlternationMatch;

                            AlternationBranch1:
                            pos = alternation_starting_pos;
                            slice = inputSpan.Slice(pos);
                        }

                        // Branch 2
                        {
                            if ((uint)slice.Length < 5 ||
                                !slice.StartsWith("index".AsSpan(), StringComparison.OrdinalIgnoreCase)) // Match the string "index" (ordinal case-insensitive)
                            {
                                goto AlternationBranch2;
                            }

                            pos += 5;
                            slice = inputSpan.Slice(pos);
                            goto AlternationMatch;

                            AlternationBranch2:
                            pos = alternation_starting_pos;
                            slice = inputSpan.Slice(pos);
                        }

                        // Branch 3
                        {
                            if ((uint)slice.Length < 6 ||
                                !slice.StartsWith("remove".AsSpan(), StringComparison.OrdinalIgnoreCase)) // Match the string "remove" (ordinal case-insensitive)
                            {
                                goto AlternationBranch3;
                            }

                            pos += 6;
                            slice = inputSpan.Slice(pos);
                            goto AlternationMatch;

                            AlternationBranch3:
                            pos = alternation_starting_pos;
                            slice = inputSpan.Slice(pos);
                        }

                        // Branch 4
                        {
                            if ((uint)slice.Length < 6 ||
                                !slice.StartsWith("search".AsSpan(), StringComparison.OrdinalIgnoreCase)) // Match the string "search" (ordinal case-insensitive)
                            {
                                goto AlternationBranch4;
                            }

                            pos += 6;
                            slice = inputSpan.Slice(pos);
                            goto AlternationMatch;

                            AlternationBranch4:
                            pos = alternation_starting_pos;
                            slice = inputSpan.Slice(pos);
                        }

                        // Branch 5
                        {
                            if ((uint)slice.Length < 3 ||
                                !slice.StartsWith("add".AsSpan(), StringComparison.OrdinalIgnoreCase)) // Match the string "add" (ordinal case-insensitive)
                            {
                                goto AlternationBranch5;
                            }

                            pos += 3;
                            slice = inputSpan.Slice(pos);
                            goto AlternationMatch;

                            AlternationBranch5:
                            pos = alternation_starting_pos;
                            slice = inputSpan.Slice(pos);
                        }

                        // Branch 6
                        {
                            if ((uint)slice.Length < 8 ||
                                !slice.StartsWith("exchange".AsSpan(), StringComparison.OrdinalIgnoreCase)) // Match the string "exchange" (ordinal case-insensitive)
                            {
                                goto AlternationBranch6;
                            }

                            pos += 8;
                            slice = inputSpan.Slice(pos);
                            goto AlternationMatch;

                            AlternationBranch6:
                            pos = alternation_starting_pos;
                            slice = inputSpan.Slice(pos);
                        }

                        // Branch 7
                        {
                            if ((uint)slice.Length < 9 ||
                                !slice.StartsWith("decrement".AsSpan(), StringComparison.OrdinalIgnoreCase)) // Match the string "decrement" (ordinal case-insensitive)
                            {
                                goto AlternationBranch7;
                            }

                            pos += 9;
                            slice = inputSpan.Slice(pos);
                            goto AlternationMatch;

                            AlternationBranch7:
                            pos = alternation_starting_pos;
                            slice = inputSpan.Slice(pos);
                        }

                        // Branch 8
                        {
                            if ((uint)slice.Length < 9 ||
                                !slice.StartsWith("increment".AsSpan(), StringComparison.OrdinalIgnoreCase)) // Match the string "increment" (ordinal case-insensitive)
                            {
                                return false; // The input didn't match.
                            }

                            pos += 9;
                            slice = inputSpan.Slice(pos);
                        }

                        AlternationMatch:;
                    }

                    // The input matched.
                    base.runtextpos = pos;
                    base.Capture(0, matchStart, pos);
                    return true;
                }
            }
        }

    }

    /// <summary>Helper methods used by generated <see cref="Regex"/>-derived implementations.</summary>
    [GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "7.0.10.26716")]
    internal static class Utilities
    {
        /// <summary>Default timeout value set in <see cref="AppContext"/>, or <see cref="Regex.InfiniteMatchTimeout"/> if none was set.</summary>
        internal static readonly TimeSpan s_defaultTimeout = AppContext.GetData("REGEX_DEFAULT_MATCH_TIMEOUT") is TimeSpan timeout ? timeout : Regex.InfiniteMatchTimeout;

        /// <summary>Whether <see cref="s_defaultTimeout"/> is non-infinite.</summary>
        internal static readonly bool s_hasTimeout = s_defaultTimeout != Timeout.InfiniteTimeSpan;
    }
}
