//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatorImaging.StaticMemberAnalyzer.Analysis {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SatorImaging.StaticMemberAnalyzer.Analysis.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Static Field Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0001__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0001__MD_TITLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static field declaration order is wrong. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0001_Description {
            get {
                return ResourceManager.GetString("SMA0001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is used before it&apos;s initialized. Reorder declarations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0001_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading Uninitialized Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0001_Title {
            get {
                return ResourceManager.GetString("SMA0001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trying to read value from static field declared in cross-referencing type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0002_Description {
            get {
                return ResourceManager.GetString("SMA0002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; cross-references static field in &apos;{1}&apos;. Initialization order is unpredictable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0002_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cross Referencing across Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0002_Title {
            get {
                return ResourceManager.GetString("SMA0002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialization order of partial type files is undefined in language spec. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0003_Description {
            get {
                return ResourceManager.GetString("SMA0003_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is declared in another partial file. Initialization order is undefined に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0003_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0003_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static Member Declared in Another File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0003_Title {
            get {
                return ResourceManager.GetString("SMA0003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static field is read before initialize. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0004_Description {
            get {
                return ResourceManager.GetString("SMA0004_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; reads this member before its declaration. Move it after に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0004_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0004_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Late Declaration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0004_Title {
            get {
                return ResourceManager.GetString("SMA0004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   `TSelf` Type Arg Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0010__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0010__MD_TITLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   `TSelf` type arg should be pointing itself. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0010_Description {
            get {
                return ResourceManager.GetString("SMA0010_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TSelf should point to itself, did you mean &apos;{0}&apos;? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0010_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0010_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TSelf is Not Self に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0010_Title {
            get {
                return ResourceManager.GetString("SMA0010_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   `TSelf` type arg should be pointing itself or its base type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0011_Description {
            get {
                return ResourceManager.GetString("SMA0011_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TSelf should point to itself or base type, did you mean &apos;{0}&apos;? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0011_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0011_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TSelf is Not Self or Base に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0011_Title {
            get {
                return ResourceManager.GetString("SMA0011_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   `TSelf` type arg should be pointing itself or its derived type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0012_Description {
            get {
                return ResourceManager.GetString("SMA0012_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TSelf should point to itself or derived type, did you mean &apos;{0}&apos;? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0012_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0012_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TSelf is Not Self or Derived に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0012_Title {
            get {
                return ResourceManager.GetString("SMA0012_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   `TSelf` type constraint is not pointing itself. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0015_Description {
            get {
                return ResourceManager.GetString("SMA0015_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TSelf constraint should point to itself, did you mean &apos;{0}&apos;? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0015_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0015_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TSelf Constraint is Not Self に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0015_Title {
            get {
                return ResourceManager.GetString("SMA0015_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enum Type Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0020__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0020__MD_TITLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unchecked value conversion to enum type. Add suppression comment &quot;// Allow enum conversion [Reason(optional)]&quot; to suppress this diagnostic. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0020_Description {
            get {
                return ResourceManager.GetString("SMA0020_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unchecked value cast to enum &apos;{0}&apos;. Centralize and verify in a utility method. Suppress with &quot;// Allow enum conversion [Reason]&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0020_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0020_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unchecked Cast to Enum Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0020_Title {
            get {
                return ResourceManager.GetString("SMA0020_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Casting enum type to other. Add suppression comment &quot;// Allow enum conversion [Reason(optional)]&quot; to suppress this diagnostic. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0021_Description {
            get {
                return ResourceManager.GetString("SMA0021_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Casting enum &apos;{0}&apos; to another type. Centralize in a utility method. Suppress with &quot;// Allow enum conversion [Reason]&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0021_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0021_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cast from Enum Type to Other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0021_Title {
            get {
                return ResourceManager.GetString("SMA0021_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unchecked value conversion to generic enum type. Add suppression comment &quot;// Allow enum conversion [Reason(optional)]&quot; to suppress this diagnostic. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0022_Description {
            get {
                return ResourceManager.GetString("SMA0022_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unchecked value cast to generic enum &apos;{0}&apos;. Centralize and verify in a utility method. Suppress with &quot;// Allow enum conversion [Reason]&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0022_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0022_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unchecked Cast to Generic Enum Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0022_Title {
            get {
                return ResourceManager.GetString("SMA0022_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Casting generic enum type to other. Add suppression comment &quot;// Allow enum conversion [Reason(optional)]&quot; to suppress this diagnostic. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0023_Description {
            get {
                return ResourceManager.GetString("SMA0023_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Casting generic enum &apos;{0}&apos; to another type. Centralize in a utility method. Suppress with &quot;// Allow enum conversion [Reason]&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0023_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0023_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cast from Generic Enum Type to Other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0023_Title {
            get {
                return ResourceManager.GetString("SMA0023_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trying to convert enum value to string. Add suppression comment &quot;// Allow enum conversion [Reason(optional)]&quot; to suppress this diagnostic. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0024_Description {
            get {
                return ResourceManager.GetString("SMA0024_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; string representation may break after obfuscation. Centralize enum-to-string handling. Suppress with &quot;// Allow enum conversion [Reason]&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0024_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0024_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enum to String に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0024_Title {
            get {
                return ResourceManager.GetString("SMA0024_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calling enum system method. Add suppression comment &quot;// Allow enum conversion [Reason(optional)]&quot; to suppress this diagnostic. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0025_Description {
            get {
                return ResourceManager.GetString("SMA0025_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Centralize enum system method calls in a utility class. Suppress with &quot;// Allow enum conversion [Reason]&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0025_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0025_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enum System Method に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0025_Title {
            get {
                return ResourceManager.GetString("SMA0025_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enum obfuscation should have controlled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0026_Description {
            get {
                return ResourceManager.GetString("SMA0026_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add &apos;Obfuscation&apos; attribute to prevent enum name changes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0026_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0026_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enum Obfuscation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0026_Title {
            get {
                return ResourceManager.GetString("SMA0026_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enum w/o `Flags` attribute should be defined as usual. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0027_Description {
            get {
                return ResourceManager.GetString("SMA0027_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Non-Flags enum should use int type without explicit index values に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0027_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0027_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unusual Enum Definition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0027_Title {
            get {
                return ResourceManager.GetString("SMA0027_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enum-like pattern implementation is not complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0028_Description {
            get {
                return ResourceManager.GetString("SMA0028_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enum-like type &apos;{0}&apos;
        ///&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0028_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0028_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Enum-like Pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0028_Title {
            get {
                return ResourceManager.GetString("SMA0028_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Struct Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0030__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0030__MD_TITLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Constructor has declared explicitly so should not use parameter-less one. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0030_Description {
            get {
                return ResourceManager.GetString("SMA0030_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use the explicit constructor for &apos;{0}&apos; instead of parameter-less default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0030_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0030_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Struct Constructor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0030_Title {
            get {
                return ResourceManager.GetString("SMA0030_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mutable struct type should not be set to `readonly` field. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0031_Description {
            get {
                return ResourceManager.GetString("SMA0031_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is mutable struct. Don&apos;t assign it to a readonly field に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0031_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0031_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mutable Struct Field marked as Read-Only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0031_Title {
            get {
                return ResourceManager.GetString("SMA0031_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Implicit conversion from struct to reference type (including interface) causes boxing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0032_Description {
            get {
                return ResourceManager.GetString("SMA0032_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Implicit boxing from &apos;{0}&apos; to &apos;{1}&apos;. Consider using generic constraint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0032_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0032_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Implicit Boxing Conversion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0032_Title {
            get {
                return ResourceManager.GetString("SMA0032_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Disposable Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0040__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0040__MD_TITLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   `using` statement should be used for instance that has public `Dispose` or `DisposeAsync` method. Add suppression comment &quot;// Don&apos;t dispose [Reason(optional)]&quot; to suppress this diagnostic. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0040_Description {
            get {
                return ResourceManager.GetString("SMA0040_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; implements IDisposable pattern. Wrap with &apos;using&apos; statement. Suppress with &quot;// Don&apos;t dispose [Reason]&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0040_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0040_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing Using Statement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0040_Title {
            get {
                return ResourceManager.GetString("SMA0040_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disposable object is assigned null without a preceding .Dispose() or ?.Dispose() call. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0041_Description {
            get {
                return ResourceManager.GetString("SMA0041_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Read-Only Variable Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0060__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0060__MD_TITLE__", resourceCulture);
            }
        }

        /// <summary>
        ///   Avoid assignments to locals unless the local is intentionally mutable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0060_Description {
            get {
                return ResourceManager.GetString("SMA0060_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Local &apos;{0}&apos; is immutable. Rename to &apos;mut_{0}&apos; to allow reassignment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0060_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0060_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Avoid Reassigning Locals に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0060_Title {
            get {
                return ResourceManager.GetString("SMA0060_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Avoid assignments to parameters unless the parameter is intentionally mutable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0061_Description {
            get {
                return ResourceManager.GetString("SMA0061_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Parameter &apos;{0}&apos; is immutable. Rename to &apos;mut_{0}&apos; to allow reassignment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0061_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0061_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Avoid Reassigning Parameters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0061_Title {
            get {
                return ResourceManager.GetString("SMA0061_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Avoid passing local/parameter-rooted variables to method/indexer calls in writable forms unless explicitly mutable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0062_Description {
            get {
                return ResourceManager.GetString("SMA0062_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   &apos;{0}&apos; is immutable. Cannot pass as writable argument に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0062_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0062_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Avoid Passing Writable Variables to Calls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0062_Title {
            get {
                return ResourceManager.GetString("SMA0062_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Avoid accessing properties of immutable variables. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0063_Description {
            get {
                return ResourceManager.GetString("SMA0063_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Property '{0}' may mutate immutable '{1}'. Rename to 'mut_{1}' to allow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0063_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0063_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Property Access on Immutable Variable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0063_Title {
            get {
                return ResourceManager.GetString("SMA0063_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Avoid calling methods of immutable variables. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0064_Description {
            get {
                return ResourceManager.GetString("SMA0064_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Method '{0}' may mutate immutable '{1}'. Rename to 'mut_{1}' to allow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0064_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0064_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Method Call on Immutable Variable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0064_Title {
            get {
                return ResourceManager.GetString("SMA0064_Title", resourceCulture);
            }
        }




        /// <summary>
        ///   Call .Dispose() on &apos;{0}&apos; before assigning null に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0041_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0041_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Null Assignment to Disposable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0041_Title {
            get {
                return ResourceManager.GetString("SMA0041_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   A locally declared disposable object must be returned on all code paths. Add suppression comment &quot;// Don&apos;t dispose [Reason(optional)]&quot; to suppress this diagnostic. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0042_Description {
            get {
                return ResourceManager.GetString("SMA0042_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Disposable &apos;{0}&apos; is not returned on all code paths. May leak. Suppress with &quot;// Don&apos;t dispose [Reason]&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0042_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0042_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Not All Code Paths Return a Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0042_Title {
            get {
                return ResourceManager.GetString("SMA0042_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   File Structure Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0050__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0050__MD_TITLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File should start with a header comment such as &apos;//&apos; or &apos;/*&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0050_Description {
            get {
                return ResourceManager.GetString("SMA0050_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a file header comment (// or /*) at the top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0050_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0050_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing File Header Comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0050_Title {
            get {
                return ResourceManager.GetString("SMA0050_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Obsolete] Annotating and Underling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9000__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA9000__MD_TITLE__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw underline in IDE. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9000_Description {
            get {
                return ResourceManager.GetString("SMA9000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [identifier] {0}
        ///&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9000_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9000_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underlining on Identifier Symbols に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9000_Title {
            get {
                return ResourceManager.GetString("SMA9000_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw underline in IDE. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9001_Description {
            get {
                return ResourceManager.GetString("SMA9001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [localvar] {0}
        ///&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9001_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underlining on Local Variables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9001_Title {
            get {
                return ResourceManager.GetString("SMA9001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw underline in IDE. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9002_Description {
            get {
                return ResourceManager.GetString("SMA9002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [param] {0}
        ///&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9002_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underlining on Method or Lambda Parameters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9002_Title {
            get {
                return ResourceManager.GetString("SMA9002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw underline in IDE. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9010_Description {
            get {
                return ResourceManager.GetString("SMA9010_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [declaration] {0}
        ///&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9010_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9010_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underlining on Declarations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9010_Title {
            get {
                return ResourceManager.GetString("SMA9010_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw underline in IDE. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9015_Description {
            get {
                return ResourceManager.GetString("SMA9015_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [designated] {0}
        ///&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9015_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9015_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underlining only on Designated Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9015_Title {
            get {
                return ResourceManager.GetString("SMA9015_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw underline in IDE. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9020_Description {
            get {
                return ResourceManager.GetString("SMA9020_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [linehead] {0}
        ///&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9020_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9020_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underlining at Line Head に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9020_Title {
            get {
                return ResourceManager.GetString("SMA9020_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw underline in IDE. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9021_Description {
            get {
                return ResourceManager.GetString("SMA9021_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [linelead] {0}
        ///&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9021_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9021_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underlining at Line Leading に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9021_Title {
            get {
                return ResourceManager.GetString("SMA9021_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw underline in IDE. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9022_Description {
            get {
                return ResourceManager.GetString("SMA9022_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [linefill] {0}
        ///&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9022_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9022_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underlining on Identifier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9022_Title {
            get {
                return ResourceManager.GetString("SMA9022_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw underline in IDE. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9023_Description {
            get {
                return ResourceManager.GetString("SMA9023_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [lineend] {0}
        ///&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9023_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9023_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underlining at Line End に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9023_Title {
            get {
                return ResourceManager.GetString("SMA9023_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw underline in IDE. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9100_Description {
            get {
                return ResourceManager.GetString("SMA9100_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1} ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9100_MessageFormat {
            get {
                return ResourceManager.GetString("SMA9100_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underlining as Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA9100_Title {
            get {
                return ResourceManager.GetString("SMA9100_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Argument Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA8000__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA8000__MD_TITLE__", resourceCulture);
            }
        }

        /// <summary>
        ///   Literal arguments should be passed as named arguments to express their meaning. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA8000_Description {
            get {
                return ResourceManager.GetString("SMA8000_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Pass literal for &apos;{0}&apos; as named argument for readability に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA8000_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8000_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Literal should be passed as named argument に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA8000_Title {
            get {
                return ResourceManager.GetString("SMA8000_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   All disposable fields must be disposed in the Dispose method. Add suppression comment &quot;// Don&apos;t dispose [Reason(optional)]&quot; to suppress this diagnostic. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0043_Description {
            get {
                return ResourceManager.GetString("SMA0043_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   &apos;{0}&apos; is not disposed. Add disposal in Dispose method. Suppress with &quot;// Don&apos;t dispose [Reason]&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0043_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0043_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Undisposed Member に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0043_Title {
            get {
                return ResourceManager.GetString("SMA0043_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Types that own disposable fields should implement the IDisposable pattern. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0044_Description {
            get {
                return ResourceManager.GetString("SMA0044_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   &apos;{0}&apos; owns disposable members. Implement Dispose method に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0044_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0044_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Missing Dispose Implementation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0044_Title {
            get {
                return ResourceManager.GetString("SMA0044_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Types that own disposable fields should implement IDisposable interface. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0045_Description {
            get {
                return ResourceManager.GetString("SMA0045_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   &apos;{0}&apos; owns disposable members. Implement IDisposable interface に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0045_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0045_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Missing IDisposable Interface に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0045_Title {
            get {
                return ResourceManager.GetString("SMA0045_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Task Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0070__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA0070__MD_TITLE__", resourceCulture);
            }
        }

        /// <summary>
        ///   Task local variable should be awaited or returned. Add suppression comment &quot;// Don&apos;t await [Reason(optional)]&quot; to suppress this diagnostic. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0070_Description {
            get {
                return ResourceManager.GetString("SMA0070_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Task &apos;{0}&apos; is not awaited. Add &apos;await&apos; or return it. Suppress with &quot;// Don&apos;t await [Reason]&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0070_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0070_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Task Not Awaited に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0070_Title {
            get {
                return ResourceManager.GetString("SMA0070_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Task local variable should be awaited or returned on all code paths. Add suppression comment &quot;// Don&apos;t await [Reason(optional)]&quot; to suppress this diagnostic. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0071_Description {
            get {
                return ResourceManager.GetString("SMA0071_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Task &apos;{0}&apos; is not awaited on all code paths. May fire-and-forget. Suppress with &quot;// Don&apos;t await [Reason]&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0071_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0071_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Task Not Awaited on All Paths に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0071_Title {
            get {
                return ResourceManager.GetString("SMA0071_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Coding Assistance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA7000__MD_TITLE__ {
            get {
                return ResourceManager.GetString("SMA7000__MD_TITLE__", resourceCulture);
            }
        }

        ///   All system primitive numbers, from byte to decimal, should be declared explicitly typed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA8001_Description {
            get {
                return ResourceManager.GetString("SMA8001_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Lambda declaration should be static to avoid unnecessary allocations. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA7000_Description {
            get {
                return ResourceManager.GetString("SMA7000_Description", resourceCulture);
            }
        }

        ///   Declare &apos;{0}&apos; with explicit number type instead of &apos;var&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA8001_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8001_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Lambda declaration is not &apos;static&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA7000_MessageFormat {
            get {
                return ResourceManager.GetString("SMA7000_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Lambda should be static に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA7000_Title {
            get {
                return ResourceManager.GetString("SMA7000_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Older runtime inefficiently handle direct passing of method. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA7001_Description {
            get {
                return ResourceManager.GetString("SMA7001_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Implicit conversion to &apos;{0}&apos; delegate causes allocation on older runtime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA7001_MessageFormat {
            get {
                return ResourceManager.GetString("SMA7001_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Implicit conversion to delegate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA7001_Title {
            get {
                return ResourceManager.GetString("SMA7001_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Non-static lambda declaration and implicit conversion causes allocation. Add suppression comment &quot;// Allow allocation [Reason(optional)]&quot; to suppress this diagnostic. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA7002_Description {
            get {
                return ResourceManager.GetString("SMA7002_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Non-static lambda causes allocation. Make it static or cache. Suppress with &quot;// Allow allocation [Reason]&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA7002_MessageFormat {
            get {
                return ResourceManager.GetString("SMA7002_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Lambda allocation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA7002_Title {
            get {
                return ResourceManager.GetString("SMA7002_Title", resourceCulture);
            }
        }

        ///   Explicit number declaration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA8001_Title {
            get {
                return ResourceManager.GetString("SMA8001_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Null suppression should be fenced with 3 parentheses for visibility, or use Debug.Assert for safe null check. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA8002_Description {
            get {
                return ResourceManager.GetString("SMA8002_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Fence &apos;!&apos; with 3 parentheses, or use Debug.Assert({0} is not null) instead に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA8002_MessageFormat {
            get {
                return ResourceManager.GetString("SMA8002_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Null suppression operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA8002_Title {
            get {
                return ResourceManager.GetString("SMA8002_Title", resourceCulture);
            }
        }
    }
}
