name: Auto dot-github Sync

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  CENTRAL_REPO: ${{ github.repository_owner }}/.github
  WORKDIR: dot-github-sync
  TARGET_DIR: .github
  GH_TOKEN: ${{ github.token }}  # For gh command

jobs:
  sync:
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            ${{ env.TARGET_DIR }}
          sparse-checkout-cone-mode: true

      - uses: actions/checkout@v6
        with:
          repository: ${{ env.CENTRAL_REPO }}
          path: ${{ env.WORKDIR }}
          sparse-checkout: |
            ${{ env.TARGET_DIR }}
          sparse-checkout-cone-mode: true

      - name: Sync all files (additive)
        run: |
          mkdir -p "$TARGET_DIR"
          rsync -av "$WORKDIR/$TARGET_DIR/" "$TARGET_DIR/"

      - name: Commit + Push + Create PR
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          TS=$(date -u +"%Y%m%d-%H%M%S")
          BRANCH="bot/$WORKDIR-${TS}"

          git checkout -B "$BRANCH"
          git add "$TARGET_DIR"

          git diff --cached --quiet && exit 0

          git commit -m "[bot] Sync \`${TARGET_DIR}\` ($TS)"
          git push origin "$BRANCH"

          gh pr create \
            --head "$BRANCH" \
            --base main \
            --fill
