name: Resource Update

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

env:
  unity_folder: 'Unity'  # no spaces!
  GH_TOKEN: ${{ github.token }}  # for github CLI
  docsgen_file_name: 'RULES.md'

jobs:

  test:
    uses: ./.github/workflows/test.yml

  resource-update:
    needs: test
    if: success()

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '10.0.x' ]

    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - run: dotnet restore
    - run: dotnet build -c Release --no-restore

    # Required for nuget-push action
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.job }}-attempt${{ github.run_attempt }}
        path: |
          src/**/Release/*.nupkg
          src/**/*.Designer.cs
          src/**/*.resx

    - name: Create PR
      run: |
        ls -al

        echo "================================"
        echo " Git setup"
        echo "================================"

        git config --global user.name  "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # To omit `--set-upstream origin` for git push
        git config --global --add --bool push.autoSetupRemote true
        git fetch --all

        BRANCH="bot/${{ github.job }}"

        ### No "create-remote-if-not-exists" option!!
        git switch "$BRANCH" || git switch -c "$BRANCH"
        git pull || true
        git branch -vv

        echo "================================"
        echo " Run DocsGen"
        echo "================================"

        dotnet run -c Release ./eng/DocsGen.cs \
          "./src/analysis/Resources.resx" \
          "./${{ env.docsgen_file_name }}"

        git add -f ${{ env.docsgen_file_name }}

        # .resx and .Designer.cs (no -f)
        git add ./src

        # Trailing slash is required to sync (copy) contents instead of directory
        rsync -avr --existing --checksum \
          ./src/packaging/bin/Release/*/ \
          ${{ env.unity_folder }}

        git add -f --update --ignore-removal ${{ env.unity_folder }}

        echo "================================"
        echo " Create PR"
        echo "================================"

        TS=$(date -u +"%Y%m%d-%H%M%S")

        git commit -m "[bot] Resource Update ($TS)" || true
        git push || true
        gh pr create -B main --fill || true
