name: 'Test and Coverage Report'

on:
  push:
    branches: [ main ]
    paths: [ 'src/**/*' ]
  pull_request:
    branches: [ main ]
    paths: [ 'src/**/*' ]
  workflow_dispatch:

env:
  TEST_PROJECT: src/StaticMemberAnalyzer.Test
  TEST_OUTPUT: TestResults
  REPORT_OUTPUT: CoverageReport

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Required for worktree
          path: current

      - if: github.ref != 'refs/heads/main'
        run: |
          cd current
          git fetch origin main
          git worktree add ../baseline origin/main

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Test with coverage
        run: |
          set -e

          # Create baseline report first
          for dir in baseline current; do
            if [ -d "$dir" ]; then
              dotnet restore "$dir/$TEST_PROJECT"
              dotnet add "$dir/$TEST_PROJECT" package coverlet.collector

              dotnet test "$dir/$TEST_PROJECT" \
                --collect:"XPlat Code Coverage" \
                --results-directory "$dir/$TEST_OUTPUT" \
                || true  # Test on main branch may fail
            fi
          done

      - name: Generate coverage report
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool

          reportDir="$TEST_OUTPUT/**/coverage.cobertura.xml"
          reportTypes="Html;MarkdownSummary;MarkdownSummaryGithub"

          if [ ! -d "baseline/$reportDir" ]; then
            {
              echo "⚠ Baseline test for coverage diff generation was failed or skipped."
              echo
            } >> $GITHUB_STEP_SUMMARY
          else
            reportgenerator \
              -reporttypes:"$reportTypes" \
              -reports:"current/$reportDir" \
              -historydir:"baseline/$reportDir" \
              -targetdir:"$REPORT_OUTPUT/diff"
            {
              cat "$REPORT_OUTPUT/diff/SummaryGithub.md" \
                | sed 's/<details open>/<details>/g' \
                | sed -E 's/- ([0-9.]+%)<\/summary>/- __\1__<\/summary>/g' \
                | sed 's/^# Summary$/# 📊 PR Changes/'
              echo
            } >> $GITHUB_STEP_SUMMARY
          fi

          # Ignore test failure on main brunch, but PR branch
          reportgenerator \
            -reporttypes:"$reportTypes" \
            -reports:"current/$reportDir" \
            -targetdir:"$REPORT_OUTPUT/full"
          cat "$REPORT_OUTPUT/full/SummaryGithub.md" \
            | sed 's/<details open>/<details>/g' \
            | sed -E 's/- ([0-9.]+%)<\/summary>/- __\1__<\/summary>/g' \
            | sed 's/^# Summary$/# 📊 Total Coverage/' \
            >> $GITHUB_STEP_SUMMARY
