name: 'Test and Coverage Report'

on:
  push:
    branches: [ main ]
    paths-ignore: [ '.github/**', 'assets/**' ]
  pull_request:
    paths-ignore: [ '.github/**', 'assets/**' ]
  workflow_dispatch:

env:
  TEST_PROJECT: ./test
  TEST_OUTPUT: TestResults
  REPORT_OUTPUT: CoverageReport

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ACTION_BRANCH (PR or event target branch)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Required for worktree
          path: ACTION_BRANCH
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Create merge-base worktree
        if: github.event_name == 'pull_request'
        working-directory: ACTION_BRANCH
        run: |
          set -euo pipefail

          BASE_REF=${{ github.event.pull_request.base.ref }}
          HEAD_SHA=${{ github.event.pull_request.head.sha }}

          git fetch origin "$BASE_REF"

          MERGE_BASE=$(git merge-base \
            "origin/$BASE_REF" \
            "$HEAD_SHA")

          echo "MERGE_BASE=$MERGE_BASE"

          git worktree add ../BASE_BRANCH $MERGE_BASE

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Test with coverage
        run: |
          set -e

          # Create BASE_BRANCH report first
          for dir in BASE_BRANCH ACTION_BRANCH; do
            if [ -d "$dir" ]; then
              dotnet restore "$dir/$TEST_PROJECT"
              dotnet add "$dir/$TEST_PROJECT" package coverlet.collector

              dotnet test "$dir/$TEST_PROJECT" \
                --collect:"XPlat Code Coverage" \
                --logger "trx" \
                --results-directory "$dir/$TEST_OUTPUT" \
                || [ "$dir" == "BASE_BRANCH" ]  # Ignore error on main branch
            fi
          done

      - name: Generate coverage report
        run: |
          sudo apt update
          sudo apt install ripgrep
          dotnet tool install -g dotnet-reportgenerator-globaltool

          generate_report () {
            local target_dir="$1"
            local out_dir="$2"
            local title="$3"
            local history_dir="$4"

            local -a report_opts=()

            if [ -n "$history_dir" ]; then
              report_opts+=("-historydir:$history_dir")
            fi

            reportgenerator \
              -reporttypes:"Html;MarkdownSummary;MarkdownSummaryGithub" \
              -reports:"$target_dir/$TEST_OUTPUT/**/coverage.cobertura.xml" \
              "${report_opts[@]}" \
              -targetdir:"$out_dir"

            FILE_COUNT=$(rg --files "$target_dir" -g '*.cs' | wc -l | tr -d ' ')
            LINE_COUNT=$(rg --files "$target_dir" -g '*.cs' \
              | xargs -r wc -l \
              | awk '{sum += $1} END {print sum+0}')
            TEST_COUNT=$(find "$target_dir" -name "*.trx" -exec grep -hoE 'total="[0-9]+"' {} + \
              | sed -E 's/total="([0-9]+)"/\1/' \
              | awk '{s+=$1} END {print s}'
            )

            FILE_COUNT=$(LC_ALL=en_US.UTF-8 numfmt --grouping "$FILE_COUNT")
            LINE_COUNT=$(LC_ALL=en_US.UTF-8 numfmt --grouping "$LINE_COUNT")
            TEST_COUNT=$(LC_ALL=en_US.UTF-8 numfmt --grouping "$TEST_COUNT")

            {
              sed \
                -e 's/<details open>/<details>/g' \
                -e 's|- \([0-9.]+%\)</summary>|- <b>\1</b></summary>|g' \
                -e "s/^# Summary$/# 📊 $title/" \
                "$out_dir/SummaryGithub.md"

              echo
              echo "🧪 Total test count: $TEST_COUNT  "
              echo "🗃️ Total file count: $FILE_COUNT  "
              echo "📑 Total line count: $LINE_COUNT  "
              echo
            } >> "$GITHUB_STEP_SUMMARY"
          }

          COV_BRANCH=BASE_BRANCH
          COV_TITLE="Base Commit Coverage"

          if [ -d "BASE_BRANCH/$TEST_OUTPUT" ]; then
            generate_report ACTION_BRANCH "$REPORT_OUTPUT/diff" "PR Coverage" \
              "BASE_BRANCH/$TEST_OUTPUT"
          else
            COV_BRANCH=ACTION_BRANCH
            COV_TITLE="Total Coverage"
            {
              echo "⚠ Baseline test for coverage diff generation was failed or skipped."
              echo
            } >> $GITHUB_STEP_SUMMARY
          fi

          generate_report "$COV_BRANCH" "$REPORT_OUTPUT/full" "$COV_TITLE" ""
